### PR TITLE
feat: upgrade to elm 0.19

### PR DESCRIPTION
**Pull request by RavenDream**
1. Create a copy the user's tree into a temporary build directory. This avoids modifying the user's elm.json in place for the duration of generating the coverage report.
   * Copy the `./elm.json` file to `.coverage/instrumented/elm.json`
   * Convert the source directory paths into absolute paths except for the src folder that elm-instrument modified.
   * copy the `./tests` folder into `.coverage/instrumented/tests
   * Add the Coverage.elm file to the `elm.json` source directories, stop using native code and return `()` instead of `never`

2. Add a `fake-elm` script to the elm coverage package that passes arguments along to `elm make`. When `elm-coverage` invokes `elm-test` I will add the argument `--compiler=fake-elm`. The fake elm script will call `elm make` normally, then after `elm make` finishes successfully, look at the `--output` flag passed to `elm make` to modify the generated js code (In the current version of `elm-test` this file is called `elmTestOutput.js`). I will insert the old `Native.Coverage.js` impl by regex adding JS in and around the generated JS for Coverage.track.

3. Run elm-test in the `.coverage/instrumented` directory instead of project root. This causes elm-test to place its generated code in a sub directory of `.coverage`.

4. Read the generated coverage log files from the `.coverage/instrumented/elm-stuff/generated-code/elm-explorations/test` directory instead of from `.coverage`. This neatly avoids having the injected coverage tracking code be aware of its location on the filesystem. Instead it will dump the `data*.json` in the current working directory when the JS file is run. In `elm-coverage` we just need to know the location where elm-test runs the tests JS file.

To work with Elm 0.19, the codemods repo also needs this patch applied
```diff
diff --git a/eliminateRedundantAStar.js b/eliminateRedundantAStar.js
index 027f8b3..4df99f7 100644
--- a/eliminateRedundantAStar.js
+++ b/eliminateRedundantAStar.js
@@ -51,7 +51,7 @@ module.exports = function(fileInfo, api) {
                 shift.callExpression(
                     shift.memberExpression(
                         calledFunction,
-                        shift.identifier("func")
+                        shift.identifier("f")
                     ),
                     args
                 )
```

### CODE REVIEW

**Comment by RavenDream** [comment]
What am I doing wrong on windows?

**Comment by zwilias** [comment]
@RavenDream Either (or both) of these things, I'm thinking:
- child_process.spawn not playing nice on windows (I've been using `cross-spawn` instead)
- spawn not being able to locate `elm` (I think i used global installs in appveyor before)

Also, let's get rid off the code-mods, they serve no use in Elm 0.19 if we're compiling with `--optimize`. They were somewhat necessary to keep runtimes on large code-bases acceptable.

**Comment by RavenDream** [comment]
elm is available in the global scope, and we are using cross-spawn in this tool and its tests

**Comment by zwilias** [comment]
Yeah, just had a look - it appears that the `which` utility used in elm-test does not like executable node-scripts. I'm not sure whether it would work on Windows (when not running in that linux compatibility thingy) either way.

As far as I'm concerned, this means we drop Windows support for the time being.

**Pull request merged**
